bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
    resource :favorite, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: {scope: :book_id}
  
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, presence: true, length: { minimum: 2, maximum: 20 },uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def get_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book.id)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
    redirect_to book_path(book.id)
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @newbook = Book.new(book_params)
    @books = Book.all
    @user = User.find(current_user.id)
    @newbook.user_id = current_user.id
    if @newbook.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@newbook.id)
    else
      render :index
    end
  end

  def index
    @newbook = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def edit
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: books_path)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: books_path)
  end
end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @newbook = Book.new
    @user = User.find(current_user.id)
    @users = User.all
  end

  def show
    @newbook = Book.new
    @books = Book.all
    @user = User.find(params[:id])
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_newbook.html.erb
<h3>New book</h3>
<% if newbook.errors.any? %>
  <%= newbook.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% newbook.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: newbook do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>

  <p>Opinion</p>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

bookers2/app/views/books/edit.html.erb
<div class="container">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Editing Book</h2>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_with model: @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>
    
        <%= f.submit 'Update Book' %>
    <% end %>
    <%= link_to 'Show', book_path(@book.id) %>
    <%= link_to 'Back', books_path %>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'newbook', newbook: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Books</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= link_to user_path(book.user_id) do %>
                    <%= image_tag book.user.get_image, size: "100x100" %>
                  <% end %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorite_path(book), method: :delete do %>
                    <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorite_path(book), method: :post do %>
                    <i class="fa-regular fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
              <td>コメント数:<%= book.book_comments.count %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

bookers2/app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'newbook', newbook: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Book detail</h3>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @user.get_image, size: "100x100"%><br>
              <%= link_to @user.name, user_path(@book.user_id) %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
              <td><%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に消しますか？" %></td>
            <% end %>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorite_path(@book), method: :delete do %>
                  <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorite_path(@book), method: :post do %>
                  <i class="fa-regular fa-heart"></i><%= @book.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <td>コメント数<%= @book.book_comments.count %></td>
          </tr>
        </tbody>
      </table>
      <div>
        <% @book.book_comments.each do |book_comment| %>
          <%= image_tag book_comment.user.get_image, size: "100x100" %>
          <%= book_comment.user.name %>
          <%= book_comment.comment %>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
          <% end %>
        <% end %>
      </div>
      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows: '5' %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

bookers2/app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="mx-auto">
      Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

bookers2/app/views/homes/top.html.erb
<div class="container">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h2>welcome to <i class="fa-solid fa-book"></i>Bookers!!</h2>
    <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
    <p>you can share and exchange your opinions, impressions, and emotions about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <%= link_to 'Log in', new_user_session_path, class: 'btn btn-info btn-sm btn-block' %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success btn-sm btn-block' %>
      </div>
    </div>
  </div>
</div>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/acaeec5042.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-house"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-users"></i>Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-book-open"></i>Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, class: 'nav-link text-light', method: :delete do %>
                    <i class="fa-solid fa-right-from-bracket"></i>Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-house"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-link"></i>About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-right-to-bracket"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div>
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

bookers2/app/views/users/_userinfo.html.erb
<h3>User info</h3>
<%= image_tag user.get_image, size: "100x100" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fa-solid fa-user-gear"></i>
  <% end %>
</div>

bookers2/app/views/users/edit.html.erb
<div class="container">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <% if @user.errors.any? %>
      <%= @user.errors.count %>errors prohibited this obj from being saved
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </div>
      <div class="form-group">
        <label for="inputImage">Image</label><br>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      </div>
      <div class="form-group">
        <label for="inputImage">Introduction</label><br>
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction"%>
      </div>
      <%= f.submit "Update User" %>
    <% end %>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'userinfo', user: @user %>
      <%= render 'books/newbook', newbook: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Users</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= image_tag user.get_image, size: "100x100" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'userinfo', user: @user %>
      <%= render 'books/newbook', newbook: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Books</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <% if book.user_id == @user.id %>
                <td><%= link_to user_path(@user.id) do %>
                      <%= image_tag @user.get_image, size: "100x100" %>
                    <% end %></td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorite_path(book), method: :delete do %>
                    <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorite_path(book), method: :post do %>
                    <i class="fa-regular fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% end %>
                </td>
                <td>コメント数:<%= book.book_comments.count %></td>
              <% end %>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>